name: DeathSpeak
version: '0.0.0.5'
main: net.cosmiccascade.deathspeak.DeathSpeak
api-version: '1.21'

commands:
  deathspeak:
    description: Trigger DeathSpeak manually
    usage: /deathspeak <word|reload>
    permission: deathspeak.use

permissions:
  deathspeak.use:
    default: op
